apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: devfile-sample-xfhz
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: devfile-sample-xfhz
    app.kubernetes.io/part-of: ci10t-776-0086-app
  name: devfile-sample-xfhz
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: nodejs-app
      app.kubernetes.io/instance: devfile-sample-xfhz
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: nodejs-app
        app.kubernetes.io/instance: devfile-sample-xfhz
    spec:
      containers:
      - image: quay.io/pmacik-testing/ci10t-776-0086-tenant/ci10t-776-0086-app/devfile-sample-xfhz@sha256:10ad3e11c9282faf67f7f164cffe899490a0ca54b3f789ab3bd21f284d08e376
        name: my-nodejs
        ports:
        - containerPort: 3001
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 50Mi
status: {}
